from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from .tasks import Task


class Action(str, Enum):
    ACC_ZERO = "ACC_ZERO"
    ACC_FIRST = "ACC_FIRST"
    FOR_X_XS = "FOR_X_XS"
    IF_X_GT_ACC = "IF_X_GT_ACC"
    IF_X_GT_ZERO = "IF_X_GT_ZERO"
    ACC_ADD_X = "ACC_ADD_X"
    ACC_ADD_ONE = "ACC_ADD_ONE"
    ACC_SET_X = "ACC_SET_X"
    END_BLOCK = "END_BLOCK"
    RETURN_ACC = "RETURN_ACC"
    COMMIT = "COMMIT"


@dataclass(frozen=True)
class Block:
    kind: str
    statements: int = 0


@dataclass(frozen=True)
class Evaluation:
    compiled: bool
    passed: int
    total: int
    error: str | None = None

    @property
    def score(self) -> float:
        return self.passed / self.total if self.total else 0.0


class PythonMaze:
    """Tiny typed action-space over a Python function body.

    v0 deliberately exposes a small grammar. Every action is generated by the
    environment, not by the agent, so arbitrary source text cannot be injected.
    """

    def __init__(self, task: Task, max_steps: int = 12):
        self.task = task
        self.max_steps = max_steps
        self.reset()

    def reset(self) -> dict:
        self.lines: list[str] = []
        self.blocks: list[Block] = [Block("function", 0)]
        self.actions: list[Action] = []
        self.has_acc = False
        self.has_return = False
        self.done = False
        self.last_evaluation: Evaluation | None = None
        return self.observe()

    @property
    def depth(self) -> int:
        return len(self.blocks) - 1

    @property
    def inside_for(self) -> bool:
        return any(block.kind == "for" for block in self.blocks)

    def observe(self) -> dict:
        return {
            "task": self.task.name,
            "description": self.task.description,
            "depth": self.depth,
            "inside_for": self.inside_for,
            "has_acc": self.has_acc,
            "has_return": self.has_return,
            "steps": len(self.actions),
            "source": self.source(),
            "valid_actions": [a.value for a in self.valid_actions()] if not self.done else [],
        }

    def _current_block_nonempty(self) -> bool:
        return self.blocks[-1].statements > 0

    def valid_actions(self) -> tuple[Action, ...]:
        if self.done:
            return ()

        out: list[Action] = []
        if not self.has_return:
            if self.depth == 0:
                out.extend((Action.ACC_ZERO, Action.ACC_FIRST))
            if self.has_acc and self.depth < 2:
                out.append(Action.FOR_X_XS)
            if self.has_acc and self.inside_for:
                if self.depth < 2:
                    out.extend((Action.IF_X_GT_ACC, Action.IF_X_GT_ZERO))
                out.extend((Action.ACC_ADD_X, Action.ACC_ADD_ONE, Action.ACC_SET_X))
            if self.has_acc and self.depth == 0:
                out.append(Action.RETURN_ACC)

        if self.depth > 0 and self._current_block_nonempty():
            out.append(Action.END_BLOCK)

        if self.depth == 0 and self.has_return and self.lines:
            out.append(Action.COMMIT)

        return tuple(dict.fromkeys(out))

    def _append(self, text: str) -> None:
        indent = "    " * len(self.blocks)
        self.lines.append(f"{indent}{text}")
        current = self.blocks[-1]
        self.blocks[-1] = Block(current.kind, current.statements + 1)

    def _open(self, kind: str, text: str) -> None:
        self._append(text)
        self.blocks.append(Block(kind, 0))

    def step(self, action: Action | str) -> tuple[dict, float, bool, dict]:
        action = Action(action)
        if action not in self.valid_actions():
            raise ValueError(f"Invalid action {action.value}; valid={self.observe()['valid_actions']}")

        self.actions.append(action)
        reward = -0.01
        info: dict = {}

        if action == Action.ACC_ZERO:
            self._append("acc = 0")
            self.has_acc = True
        elif action == Action.ACC_FIRST:
            self._append("acc = xs[0]")
            self.has_acc = True
        elif action == Action.FOR_X_XS:
            self._open("for", "for x in xs:")
        elif action == Action.IF_X_GT_ACC:
            self._open("if", "if x > acc:")
        elif action == Action.IF_X_GT_ZERO:
            self._open("if", "if x > 0:")
        elif action == Action.ACC_ADD_X:
            self._append("acc += x")
        elif action == Action.ACC_ADD_ONE:
            self._append("acc += 1")
        elif action == Action.ACC_SET_X:
            self._append("acc = x")
        elif action == Action.END_BLOCK:
            self.blocks.pop()
        elif action == Action.RETURN_ACC:
            self._append("return acc")
            self.has_return = True
        elif action == Action.COMMIT:
            self.last_evaluation = self.evaluate()
            self.done = True
            reward += self.last_evaluation.score * 5.0
            if self.last_evaluation.compiled:
                reward += 0.25
            if self.last_evaluation.score == 1.0:
                reward += 5.0
            info["evaluation"] = self.last_evaluation

        if len(self.actions) >= self.max_steps and not self.done:
            self.done = True
            reward -= 0.5

        return self.observe(), reward, self.done, info

    def source(self) -> str:
        body = "\n".join(self.lines) if self.lines else "    pass"
        return f"def solve(xs):\n{body}\n"

    def evaluate(self) -> Evaluation:
        source = self.source()
        try:
            code = compile(source, "<mosca>", "exec", dont_inherit=True, optimize=0)
            namespace: dict = {"__builtins__": {}}
            exec(code, namespace, namespace)
            solve = namespace["solve"]
        except Exception as exc:
            return Evaluation(False, 0, len(self.task.cases), f"{type(exc).__name__}: {exc}")

        passed = 0
        first_error: str | None = None
        for case in self.task.cases:
            try:
                result = solve(*case.args)
                if result == case.expected:
                    passed += 1
                elif first_error is None:
                    first_error = f"expected {case.expected!r}, got {result!r}"
            except Exception as exc:
                if first_error is None:
                    first_error = f"{type(exc).__name__}: {exc}"

        return Evaluation(True, passed, len(self.task.cases), first_error)
